### ISSUE TITLE
"[Errno 2] No such file or directory" when running fetch_detector for "outlier" "cifar" "OutlierVAE"

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/alibi-detect#150]
When running the following code:

```
filepath = 'detector' 
from alibi_detect.utils.fetching import fetch_detector
detector_type = 'outlier'
dataset = 'cifar10'
detector_name = 'OutlierVAE'
od = fetch_detector(filepath, detector_type, dataset, detector_name)
```

I get the error:

```
Downloading data from https://storage.googleapis.com/seldon-models/alibi-detect/od/OutlierVAE/cifar10/model/encoder_net.h5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alejandro/miniconda3/lib/python3.7/site-packages/alibi_detect/utils/fetching.py", line 437, in fetch_detector
    fetch_vae(url, filepath)
  File "/home/alejandro/miniconda3/lib/python3.7/site-packages/alibi_detect/utils/fetching.py", line 234, in fetch_vae
    fetch_enc_dec(url, filepath)
  File "/home/alejandro/miniconda3/lib/python3.7/site-packages/alibi_detect/utils/fetching.py", line 98, in fetch_enc_dec
    os.path.join(url_models, 'encoder_net.h5')
  File "/home/alejandro/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 278, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/home/alejandro/miniconda3/lib/python3.7/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/alejandro/.keras/datasets/detector/OutlierVAE/model/encoder_net.h5'

```

Using:
```
> pip freeze | grep tensorflow
tensorflow==2.3.0
tensorflow-estimator==2.3.0
tensorflow-probability==0.11.0

> pip freeze | grep alibi
alibi==0.5.5
alibi-detect==0.4.3
alibiexplainer==0.3.0
```

**Comment by axsaucedo** [comment]
Ok it seems that the `filepath` just needs to be absolute instead of relative, all working, thanks :)
