### ISSUE TITLE
Error when running Adversarial AE detection demo

### ISSUE THREAD

**Issue by chenyuqi990215** [SeldonIO/alibi-detect#199]
I follow the code in https://docs.seldon.io/projects/alibi-detect/en/latest/examples/ad_ae_cifar10.html and meet the following error when running the following codes:

```
dataset = 'cifar10'
model = 'resnet56'
clf = fetch_tf_model(dataset, model)
```

```
XXX lineno: 214, opcode: 160
Traceback (most recent call last):
  File "***/alibi_test.py", line 32, in <module>
    clf = fetch_tf_model(dataset, model)
  File "***/alibi_detect/utils/fetching.py", line 77, in fetch_tf_model
    clf = tf.keras.models.load_model(save_path, custom_objects=custom_objects)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 207, in load_model
    compile)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 184, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 64, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 177, in deserialize
    printable_module_name='layer')
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 358, in deserialize_keras_object
    list(custom_objects.items())))
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2262, in from_config
    config, custom_objects=custom_objects)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 669, in from_config
    config, custom_objects)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 1285, in reconstruct_from_config
    process_node(layer, node_data)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 1233, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "***/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 917, in call
    result = self.function(inputs, **kwargs)
  File "/home/avl/git/models/official/vision/image_classification/resnet_cifar_model.py", line 214, in <lambda>
SystemError: unknown opcode
```

**Comment by jklaise** [comment]
I think this is due to a mismatch between the version of tensorflow installed and the version of tensorflow that was originally used to train this saved model, @arnaudvl do we have metadata on the version the models were trained with?
