### ISSUE TITLE
Error install from source

### ISSUE THREAD

**Issue by arisliang** [SeldonIO/alibi-detect#430]
I try to install from source by `pip install git+https://github.com/SeldonIO/alibi-detect.git`.

It gives error:

> ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ly\miniconda3\envs\ts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ly\\AppData\\Local\\Temp\\pip-req-build-r8srf411\\setup.py'"'"'; __file__='"'"'C:\\Users\\ly\\AppData\\Local\\Temp\\pip-req-build-r8srf411\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ly\AppData\Local\Temp\pip-pip-egg-info-7clmcvsi'
         cwd: C:\Users\ly\AppData\Local\Temp\pip-req-build-r8srf411\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ly\AppData\Local\Temp\pip-req-build-r8srf411\setup.py", line 22, in <module>
        long_description=readme(),
      File "C:\Users\ly\AppData\Local\Temp\pip-req-build-r8srf411\setup.py", line 6, in readme
        return f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 5548: illegal multibyte sequence

on windows 10, python 3.9.

Anything related to unicode setting on windows?

**Comment by arisliang** [comment]
Probably due to my system locale to be none-english, this error is gone after choose "Use Unicode UTF-8 for worldwide language support".

Installed from source successfully
