### ISSUE TITLE
Notebook CI failing 

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi-detect#664]
Our notebook tests are failing with:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pytest_randomly/__init__.py", line 194, in pytest_runtest_setup
    _reseed(item.config, -1)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pytest_randomly/__init__.py", line 172, in _reseed
    reseed(seed)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/thinc/util.py", line 70, in fix_random_seed
    numpy.random.seed(seed)
  File "mtrand.pyx", line 246, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 1[66](https://github.com/SeldonIO/alibi-detect/actions/runs/3257690768/jobs/5349135028#step:5:67), in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```

It appears to involve the `numpy` seed setting, `pytest_randomly`, and `thinc`. Perhaps `thinc`'s `pytest_randomly` entry point is overriding ours? 

Requires further investigation...

**Comment by ascillitoe** [comment]
For reference: https://github.com/pytest-dev/pytest-randomly/issues/495
