### ISSUE TITLE
Importing  load_detector, save_detector fails

### ISSUE THREAD

**Issue by Sandeep-Bhogaraju-TA** [SeldonIO/alibi-detect#797]
Steps with which I am able to replicate-

1) create a conda env with python=3.9
2) pip install alibi_detect[tensorflow]==0.10.3
3) import "from alibi_detect.saving import load_detector, save_detector"
4) Fails with TypeError: issubclass() arg 1 must be a class

I am also noticing it fails for latest version of alibi detect as well

Traceback that comes - 

`Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alibi_detect.saving import load_detector, save_detector
2023-05-23 16:43:23.525748: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-23 16:43:23.550082: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-23 16:43:23.550156: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sandeep/miniconda3/envs/test_alibidetect/lib/python3.9/site-packages/alibi_detect/__init__.py", line 1, in <module>
    from . import ad, cd, models, od, utils, saving
  File "/home/sandeep/miniconda3/envs/test_alibidetect/lib/python3.9/site-packages/alibi_detect/saving/__init__.py", line 1, in <module>
    from alibi_detect.saving.validate import validate_config
  File "/home/sandeep/miniconda3/envs/test_alibidetect/lib/python3.9/site-packages/alibi_detect/saving/validate.py", line 3, in <module>
    from alibi_detect.saving.schemas import (  # type: ignore[attr-defined]
  File "/home/sandeep/miniconda3/envs/test_alibidetect/lib/python3.9/site-packages/alibi_detect/saving/schemas.py", line 95, in <module>
    class DetectorConfig(CustomBaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/home/sandeep/miniconda3/envs/test_alibidetect/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
>>> `

**Comment by jklaise** [comment]
@Sandeep-Bhogaraju-TA this is an issue with one of our dependencies - #796. The workaround until it's fixed is to `pip install typing-extensions==4.5.0`.

**Comment by Sandeep-Bhogaraju-TA** [comment]
Thank you
Testing it

**Comment by jklaise** [comment]
Issue has been fixed upstream, will close.
